language: php

matrix:
  include:
    - php: 5.2
      dist: precise

php:
  - '5.2'

services:
  - mysql

before_install:
  mysql -e "CREATE DATABASE IF NOT EXISTS dnevnik"

script: phpunit --configuration ./test/phpunit.xml.dist